---
title: "Data Import"
author: "Our Group"
date: "2026-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
library(dplyr)
library(purrr)
library(stringr)
library(tidyr)
library(ggplot2)
```

```{r football}
cfb13 <- read.csv("College_Football_data/cfb13.csv")
cfb14 <- read.csv("College_Football_data/cfb14.csv")
cfb15 <- read.csv("College_Football_data/cfb15.csv")
cfb16 <- read.csv("College_Football_data/cfb16.csv")
cfb17 <- read.csv("College_Football_data/cfb17.csv")
cfb18 <- read.csv("College_Football_data/cfb18.csv")
cfb19 <- read.csv("College_Football_data/cfb19.csv")
cfb20 <- read.csv("College_Football_data/cfb20.csv")
cfb21 <- read.csv("College_Football_data/cfb21.csv")
cfb22 <- read.csv("College_Football_data/cfb22.csv")
cfb23 <- read.csv("College_Football_data/cfb23.csv")
cfb_list <- list(
  "2013" = cfb13,
  "2014" = cfb14,
  "2015" = cfb15,
  "2016" = cfb16,
  "2017" = cfb17,
  "2018" = cfb18,
  "2019" = cfb19,
  "2020" = cfb20,
  "2021" = cfb21,
  "2022" = cfb22,
  "2023" = cfb23
)


# Combine datasets
cfb_cleaned <- imap(cfb_list, ~ .x %>%
  mutate(across(everything(), as.character),
         Year = as.numeric(.y)))

cfb_all <- bind_rows(cfb_cleaned)


# Clean strings
cfb_all <- cfb_all %>%
  mutate(across(everything(), ~str_trim(.))) %>%
  mutate(across(everything(), ~str_replace_all(., "Â", ""))) %>%
  mutate(across(everything(), ~na_if(., ""))) %>%
  mutate(across(everything(), ~na_if(., "NA")))
cfb_all <- cfb_all %>%
  filter(Average.Time.of.Possession.per.Game != "Reclassifying")


# Convert time
cfb_all <- cfb_all %>%
  separate(Average.Time.of.Possession.per.Game,
           into = c("min", "sec"),
           sep = ":",
           convert = TRUE)
cfb_all <- cfb_all %>%
  mutate(avg_top_min = min + sec / 60)


champions <- tibble::tribble(
  ~Year, ~Champion,
  2013, "Florida St. (ACC)",
  2014, "Ohio St. (Big Ten)",
  2015, "Alabama (SEC)",
  2016, "Clemson (ACC)",
  2017, "Alabama (SEC)",
  2018, "Clemson (ACC)",
  2019, "LSU (SEC)",
  2020, "Alabama (SEC)",
  2021, "Georgia (SEC)",
  2022, "Georgia (SEC)",
  2023, "Michigan (Big Ten)"
)

cfb_all
```

```{r model}
cfb_model <- cfb_all %>%
  mutate(
    win_pct = as.numeric(Win) / as.numeric(Games),
    turnovers_lost = as.numeric(Turnovers.Lost),
    turnovers_gain = as.numeric(Turnovers.Gain)
  ) %>%
  select(win_pct, turnovers_lost, turnovers_gain) %>%
  na.omit()

cfb_model

model_turnovers <- lm(win_pct ~ turnovers_lost + turnovers_gain,
                     data = cfb_model)

summary(model_turnovers)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
# turnovers lost vs win%
ggplot(cfb_model, aes(x = turnovers_lost, y = win_pct)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", se = TRUE, color = "red") +
  labs(
    title = "Turnovers Lost vs Win Percentage",
    x = "Turnovers Lost",
    y = "Win Percentage"
  ) +
  theme_minimal()
```

```{r}
# turnovers won vs win%
ggplot(cfb_model, aes(x = turnovers_gain, y = win_pct)) +
  geom_point(alpha = 0.4) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") +
  labs(
    title = "Turnovers Gained vs Win Percentage",
    x = "Turnovers Gained",
    y = "Win Percentage"
  ) +
  theme_minimal()
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
